### ISSUE TITLE
undefined symbol: dbus_message_get_allow_interactive_authorization

### ISSUE THREAD

**Issue by bovlb** [mardy/docker-images#4]
So this is probably more my problem than yours, but I thought I would reach out in case you had any suggestions for me.

I have been using your docker image `mardy/qt:trusty-qt512` to build Qt applications.  IN particular, I am attempting to build an AppImage file (using `linuxdeployqt`) so that I can use the resulting Qt application in a different image (that does not have Qt installed).  I have managed to build the AppImage file, but when I try to run it I get the above error message.

Googling this message tells me that I need to upgrade to a more recent version of libdbus, but your image already has the most recent version according to `apt-get`.  Other pages tell me that I need to be using a more recent version of Ubuntu.  I understand your reasoning for using an old version.

![image](https://user-images.githubusercontent.com/31326650/89845551-ae29a000-db33-11ea-9a57-21bd2d239d5b.png)

**Comment by mardy** [comment]
Hi! Are you sure that the newer libdbus is included in the AppImage?

**Comment by bovlb** [comment]
> Hi! Are you sure that the newer libdbus is included in the AppImage?

I'm confused by your question.  Surely the problem is that the newer libdbus is _not_ being included?

Perhaps I should point out that this is my first time working with either Qt or AppImage, so I'm working in the dark here.  I'm just trying to get someone else's software running in my docker container.

**Comment by bovlb** [comment]
This thread seems to be relevant: 
https://bugreports.qt.io/browse/QTBUG-72507

**Comment by bovlb** [comment]
Aha!  I think I have fixed my problem by switching to your xenial image.  This didn't work for me the first time because other parts of the build script I got were dependent on trusty, but I worked out how to switch them to xenial.

Thanks for your help!
